apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-app-manifest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vinukavinnath/demo-spring-app-manifest.git'
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
